#!/bin/bash
#
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
  echo "Als root Angemeldet"
  #
read -p "Wollen sie einen neuen Benutzer erstellen?: [y/N] " erstellen
if [ "$erstellen" == "y" ]
  then 
    read -p "Wie soll der neue Benutzer heissen?: " user
    read -p "Welches Passwort soll "$user" bekommen?: " pass
    # adduser
    echo "adduser "$user""
    useradd $user
if [ "$1" != "n" ]; then
    mkdir -p /home/"$user"/Schreibtisch/
    cp /usr/share/applications/arch-install.desktop /home/"$user"/Schreibtisch/
    chmod +x /home/"$user"/Schreibtisch/arch-install.desktop
fi
    chmod 770 -R -v /home/"$user"/
    chown -cR "$user" /home/"$user"/
passwd $user <<EOT
$pass
$pass
EOT
#
    echo ""$user" ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      else
    read -p "Wie heisst der normale Benutzer auf dem PC?: " user
    chown -cR "$user" /home/"$user"/
    #
read -p "Soll "$user" root-rechte gegeben werden?: [y/N] " root
if [ "$root" == "y" ]
  then
    echo ""$user" ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
fi
fi
#
read -p "Ist das ein Raspberry PI ?: [y/N] " pi
read -p "Wollen sie eine Verbindung mit Ethernet aufbauen?: [y/N] " ethernet
if [ "$ethernet" == "y" ]
  then
    ip link
    read -p "Wie heisst das Ethernet-modul?: " ethernetmodul
    echo "dhcpcd wird gestartet!"
    dhcpcd "$ethernetmodul"
  else
    echo "Ethernet wird nicht eingerichtet!"
fi
#
read -p "Wollen sie eine Verbindung mit wifi verbindung aufbauen?: [y/N] " wifi
if [ "$wifi" == "y" ]
  then
    echo "Wifi wird eingerichtet!"
    ip link
    read -p "Wie heisst das wlan-modul?: " modul
    ip link set dev "$modul" up
    sleep 5
    iw dev "$modul" scan > scan.txt
    nano scan.txt
    read -p "Wie heisst das Netzwerk?: " network
    read -p "Wie heisst das Passwort?: " passwort
    wpa_passphrase  "$network"  "$passwort"  > /etc/wpa_supplicant/wpa_supplicant-"$modul".conf
    wpa_supplicant -B -i "$modul" -c /etc/wpa_supplicant/wpa_supplicant-"$modul".conf
    dhcpcd "$modul"
  else
    echo "Wifi wird nicht eingerichtet!"
fi
#
read -p "Sollen die Grundpackete installiert werden?: [Y/n] " grund
if [ "$grund" != "n" ]
  then
    echo "Grundpackete werden installiert!"
    pacman -Syu base base-devel alsa-utils devtools xorriso cdrtools squashfs-tools wget libisoburn libisofs gdisk ntfs-3g android-tools xorg xorg-apps xorg-drivers xorg-fonts xorg-twm xorg-xclock xterm ttf-dejavu xorg-server xorg-utils xorg-server-utils xorg-xinit xorg-xdm xscreensaver cdrdao links x11vnc tigervnc htop git lm_sensors sudo openssl acpid ntp dbus avahi cronie net-tools procps pacman zip gcc autoconf automake make libconfig obconf patch fakeroot pkg-config mplayer gparted pigz pixz lxde networkmanager network-manager-applet
fi
#
echo "Grundpackete2 werden installiert!"
read -p "Soll brasero mitinstalliert werden?: [Y/n] " brasero
if [ "$brasero" != "n" ]
  then
    pacman -S brasero
fi
#
read -p "Soll simple-scan mitinstalliert werden?: [Y/n] " simple
if [ "$simple" != "n" ]
  then
    pacman -S simple-scan
fi
#
read -p "Soll pulseaudio mitinstalliert werden?: [Y/n] " pulseaudio
if [ "$pulseaudio" != "n" ]
  then
    pacman -S pulseaudio pulseaudio-alsa
fi
#
read -p "Soll inkscape mitinstalliert werden?: [Y/n] " inkscape
if [ "$simple" != "n" ]
  then
    pacman -S inkscape
fi
#
read -p "Soll teeworlds mitinstalliert werden?: [Y/n] " teeworlds
if [ "$teeworlds" != "n" ]
  then
    pacman -S teeworlds
fi
#
read -p "Soll 0ad mitinstalliert werden?: [Y/n] " ad
if [ "$ad" != "n" ]
  then
    pacman -S 0ad
fi
#
read -p "Soll megaglest mitinstalliert werden?: [Y/n] " megaglest
if [ "$megaglest" != "n" ]
  then
    pacman -S megaglest
fi
#
read -p "Soll assaultcube mitinstalliert werden?: [Y/n] " assaultcube
if [ "$assaultcube" != "n" ]
  then
    pacman -S assaultcube
fi
#
read -p "Soll audacity mitinstalliert werden?: [Y/n] " audacity
if [ "$audacity" != "n" ]
  then
    pacman -S audacity
fi
#
read -p "Soll qemu mitinstalliert werden?: [Y/n] " qemu
if [ "$qemu" != "n" ]
  then
    pacman -S qemu qemu-arch-extra
fi
#
read -p "Soll cups mitinstalliert werden?: [Y/n] " cups
if [ "$cups" != "n" ]
  then
    pacman -S cups hplip python-pyqt5
    systemctl enable org.cups.cupsd.service
fi
#
read -p "Soll youtube-dl mitinstalliert werden?: [Y/n] " youtube
if [ "$youtube" != "n" ]
  then
    pacman -S youtube-dl flac ffmpeg
fi
#
read -p "Soll freeciv mitinstalliert werden?: [Y/n] " freeciv
if [ "$freeciv" != "n" ]
  then
    pacman -S freeciv
fi
#
read -p "Soll vlc mitinstalliert werden?: [Y/n] " vlc
if [ "$vlc" != "n" ]
  then
    pacman -S vlc libdvdread libdvdcss libdvdnav
fi
#
read -p "Soll transmission mitinstalliert werden?: [Y/n] " transmission
if [ "$transmission" != "n" ]
  then
    pacman -S transmission-gtk transmission-cli
fi
#
read -p "Soll scratch mitinstalliert werden?: [Y/n] " scratch
if [ "$scratch" != "n" ]
  then
    pacman -S scratch
fi
#
read -p "Soll geckodriver mitinstalliert werden?: [Y/n] " geckodriver
if [ "$geckodriver" != "n" ]
  then
    pacman -S python-pip python2-pip geckodriver
fi
#
read -p "Soll macchanger mitinstalliert werden?: [Y/n] " macchanger
if [ "$macchanger" != "n" ]
  then
    pacman -S macchanger
fi
#
read -p "Soll gimp mitinstalliert werden?: [Y/n] " gimp
if [ "$gimp" != "n" ]
  then
    pacman -S gimp
fi
#
read -p "Soll minetest mitinstalliert werden?: [Y/n] " minetest
if [ "$minetest" != "n" ]
  then
    pacman -S minetest
fi
#
read -p "Soll openssh mitinstalliert werden?: [Y/n] " openssh
if [ "$openssh" != "n" ]
  then
    pacman -S openssh
    systemctl enable sshd
fi
#
read -p "Soll firefox mitinstalliert werden?: [Y/n] " firefox
if [ "$firefox" != "n" ]
  then
    pacman -S firefox firefox-adblock-plus flashplugin
fi
#
read -p "Soll chromium mitinstalliert werden?: [Y/n] " chromium
if [ "$chromium" != "n" ]
  then
    pacman -S chromium
fi
#
read -p "Soll netbeans mitinstalliert werden?: [Y/n] " netbeans
if [ "$netbeans" != "n" ]
  then
    pacman -S netbeans jdk8-openjdk
    else
    read -p "Soll statdessen java mitinstalliert werden?: [Y/n] " java
    if [ "$java" != "n" ]
      then
      pacman -S jdk8-openjdk
fi
fi
#
read -p "Soll mumble mitinstalliert werden?: [Y/n] " mumble
if [ "$mumble" != "n" ]
  then
    pacman -S murmur mumble
    systemctl enable murmur
    read -p "Wie soll das Passwort vom murmur-server sein?: " murmurpass
    murmurd -ini /etc/murmur.ini -supw $murmurpass
fi
#
read -p "Soll libreoffice-fresh mitinstalliert werden?: [Y/n] " libreoffice
if [ "$libreoffice" != "n" ]
  then
    pacman -S libreoffice-fresh libreoffice-fresh-de
fi
#
read -p "Soll snapd mitinstalliert werden?: [Y/n] " snapd
if [ "$snapd" != "n" ]
  then
    pacman -S snapd
    systemctl enable snapd.socket
fi
#
read -p "Soll apache mitinstalliert werden?: [Y/n] " apache
if [ "$apache" != "n" ]
  then
    pacman -S apache
    systemctl enable httpd
fi
#
read -p "Sollen die Hacker-tools mitinstalliert werden?: [Y/n] " hacker
if [ "$hacker" != "n" ]
  then
    pacman -S wireshark-gtk hydra nmap pygtk aircrack-ng bless
fi
#
read -p "Sollen docker mitinstalliert werden?: [Y/n] " docker
if [ "$docker" != "n" ]
  then
    pacman -S docker
    systemctl enable docker
fi
#
echo "Packetliste1 Ende"
echo "Packetliste2 Start"
echo "Zusatspackete werden Installiert!"
#
if [ "$pi" != "y" ]
then
#
read -p "Soll Nvidia mitinstalliert werden?: [Y/n] " nvidia
if [ "$nvidia" != "n" ]
  then
    pacman -S nvidia nvidia-libgl nvidia-settings lib32-nvidia-libgl
    read -p "Soll nvidia-xconfig gestartet werden?: [Y/n] " nvidiax
      if [ "$nvidiax" != "n" ]
        then
      nvidia-xconfig   
fi  
fi
#
read -p "Soll steam mitinstalliert werden?: [Y/n] " steam
if [ "$steam" != "n" ]
  then
    pacman -S steam
fi
#
read -p "Soll wine mitinstalliert werden?: [Y/n] " wine
if [ "$wine" != "n" ]
  then
     pacman -S wine
fi
#
read -p "Soll OBS mitinstalliert werden?: [Y/n] " obs
if [ "$obs" != "n" ]
  then
     pacman -S obs-studio
fi
fi
#
if [ "$pi" == "y" ]
then
read -p "Soll der omxplayer mitinstalliert werden?: [Y/n] " omxplayer
if [ "$omxplayer" != "n" ]
  then
    pacman -S omxplayer
fi
fi
#
read -p "Soll yaourt mitinstalliert werden?: [Y/n] " yaourt
if [ "$yaourt" != "n" ]
  then
    cd /home/"$user"/
pwd
    su "$user" -c "curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz"
pwd
    su "$user" -c "tar -xvzf package-query.tar.gz"
pwd
    cd package-query
pwd
    su "$user" -c "makepkg -si"
pwd
    cd ..
pwd
    su "$user" -c "curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz"
pwd
    su "$user" -c "tar -xvzf yaourt.tar.gz"
pwd
    cd yaourt
pwd
    su "$user" -c "makepkg -si"
pwd
    cd ..
pwd
    su "$user" -c "yaourt -Syu"
    su "$user" -c "mkdir -p /home/"$user"/aur-pakete"
    su "$user" -c "yaourt -S pamac-aur --export /home/"$user"/aur-pakete"
pwd
#
read -p "Soll google-chrome mitinstalliert werden?: [Y/n] " chrome
if [ "$chrome" != "n" ]
  then
    su "$user" -c "yaourt -S google-chrome --export /home/"$user"/aur-pakete"
fi
#
read -p "Soll discord mitinstalliert werden?: [Y/n] " discord
if [ "$discord" != "n" ]
  then
    su "$user" -c "yaourt -S discord --export /home/"$user"/aur-pakete"
fi
#
read -p "Soll spotify mitinstalliert werden?: [Y/n] " spotify
if [ "$spotify" != "n" ]
  then
    su "$user" -c "yaourt -S spotify --export /home/"$user"/aur-pakete"
fi
#
read -p "Soll xboxdrv mitinstalliert werden?: [Y/n] " xboxdrv
if [ "$xboxdrv" != "n" ]
  then
    su "$user" -c "yaourt -S xboxdrv --export /home/"$user"/aur-pakete"
fi
read -p "Soll telegram mitinstalliert werden?: [Y/n] " telegram
if [ "$telegram" != "n" ]
  then
    su "$user" -c "yaourt -S telegram-desktop --export /home/"$user"/aur-pakete"
fi
fi
echo "Packetliste2 Ende"
echo "Beginne mit dem Konfigurieren des Systems :D"
# set desktop
echo "set desktops"
#
read -p "Welcher desktop soll verwendet werden? all, lxde, gnome, gnome-flashback, mate, xfce4, kde, cinnamon oder lxqt : " rootstart
if [ "$rootstart" == "gnome" ]
  then    
    pacman -S gnome gnome-extra gnuchess goobox file-roller network-manager-applet networkmanager system-config-printer blueman gnome-power-manager gnome-screensaver
    echo "exec gnome-session" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service
    
    elif [ "$rootstart" == "gnome-flashback" ]
    then
    pacman -S gnome-flashback gnome gnome-extra network-manager-applet networkmanager system-config-printer blueman gnome-power-manager gnome-screensaver
    echo "export XDG_CURRENT_DESKTOP=GNOME-Flashback:GNOME" > /etc/X11/xinit/xinitrc
    echo "exec gnome-session --session=gnome-flashback-metacity" >> /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "cinnamon" ]
    then
    pacman -S cinnamon gnome gnome-extra network-manager-applet networkmanager system-config-printer blueman gnome-power-manager gnome-screensaver
    echo "exec cinnamon-session" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "mate" ]
    then
    pacman -S mate mate-extra network-manager-applet networkmanager system-config-printer blueman mate-power-manager gtk-engine-murrine
    echo "exec mate-session" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "lxde" ]
    then
    pacman -S lxde networkmanager network-manager-applet
    echo "exec startlxde" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "lxqt" ]
    then
    pacman -S lxqt networkmanager network-manager-applet
    echo "exec startlxqt" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "xfce4" ]
    then
    pacman -S xfce4 xfce4-goodies human-icon-theme networkmanager network-manager-applet
    echo "exec startxfce4" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "kde" ]
    then
    pacman -S plasma kde-l10n-de kde-applications networkmanager network-manager-applet
    echo "exec startkde" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service

    elif [ "$rootstart" == "all" ]
    then
    pacman -S lxde cinnamon gnome gnome-extra file-roller gnuchess goobox network-manager-applet networkmanager system-config-printer blueman gnome-power-manager mate mate-extra mate-power-manager gtk-engine-murrine lxqt xfce4 xfce4-goodies human-icon-theme plasma kde-l10n-de kde-applications gnome-flashback gnome-screensaver
    echo "exec startlxde" > /etc/X11/xinit/xinitrc
    systemctl enable NetworkManager.service
      else
    echo "kein desktop erstellt!!!"
fi
#
echo "Systemsprache und dienste werden erstellt!"
# localectl set-x11-keymap de pc105 nodeadkeys
# set system startup files
echo "System startup files"
if [ "$wifi" == "y" ]
  then
    systemctl enable wpa_supplicant@"$modul".service
    systemctl enable dhcpcd@"$modul"
    else
    systemctl disable dhcpcd
fi
read -p "Soll xdm wenn der PC bootet gestartet werden?: [Y/n] " xdm
if [ "$xdm" != "n" ]
  then
  systemctl enable xdm
  else
  read -p "Soll getty den X-Server automatisch starten?: [Y/n] " getty
  if [ "$getty" != "n" ]
  then
    echo "if [ \$(tty) = "/dev/tty1" ]; then" > /root/.bash_profile
    echo "startx" >> /root/.bash_profile
    echo "fi" >> /root/.bash_profile
    #
    echo "if [ \$(tty) = "/dev/tty1" ]; then" > /home/"$user"/.bash_profile
    echo "startx" >> /home/"$user"/.bash_profile
    echo "fi" >> /home/"$user"/.bash_profile
    #
read -p "Welcher Nutzer soll automatisch gestartet werden?: [ROOT/"$user"] " start
if [ "$start" != "$user" ]
  then
    mkdir -p /etc/systemd/system/getty\@tty1.service.d
    echo "[Service]" > /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    echo "ExecStart=" >> /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    echo "ExecStart=-/sbin/agetty --noclear -a root %I 38400 linux" >> /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    systemctl enable getty@tty1
    else
    mkdir -p /etc/systemd/system/getty\@tty1.service.d
    echo "[Service]" > /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    echo "ExecStart=" >> /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    echo "ExecStart=-/sbin/agetty --noclear -a "$user" %I 38400 linux" >> /etc/systemd/system/getty\@tty1.service.d/autologin.conf
    systemctl enable getty@tty1
fi
fi
fi
systemctl enable acpid
systemctl enable ntpd
systemctl enable avahi-daemon
# set systemconfiguration
echo "systemconfiguration"
#
echo LANG=de_DE.UTF-8 > /etc/locale.conf
echo LC_COLLATE=C >> /etc/locale.conf
echo LANGUAGE=de_DE >> /etc/locale.conf
#
echo KEYMAP=de-latin1 > /etc/vconsole.conf
echo FONT=lat9w-16 >> /etc/vconsole.conf
#
echo de_DE.UTF-8 UTF-8 > /etc/locale.gen
echo de_DE ISO-8859-1 >> /etc/locale.gen
echo de_DE@euro ISO-8859-15 >> /etc/locale.gen
#
locale-gen
#
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

read -p "Sollen sonst noch Packete hinzugefügt werden? [Packetnamen] : " packete
pacman -Syu $packete
read -p "Sollen sonst noch Packete entfernt werden? [Packetnamen] : " rpackete
pacman -Rss $rpackete

#
#systemctl start ntpd
#ntpd -gq
#date
#hwclock -w
#
#xset m 2/1 0
#

echo "Fertig!!!"
