#!/bin/bash

set -ex

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    sudo $0 $1 $2 $3 $4 $5 $6 $7 $8 $9
    exit 0
fi
echo "Als root Angemeldet"


kernel1="$(echo $(find /boot/ -name "initramfs*.img") | cut -d" " -f1)"
linuz1="$(echo $(find /boot/ -name "vmlinuz*") | cut -d" " -f1)"
kernel="${kernel1#/*/}"
linuz="${linuz1#/*/}"

kernelback1="$(echo $(find /boot/ -name "initramfs*-fallback.img") | cut -d" " -f1)"
kernelback="${kernelback1#/*/}"


echo "Kernel: ${kernel}"
echo "Linuz: ${linuz}"
echo "Kernel-fallback: ${kernelback}"

sed "s|%LINUZ%|${linuz}|g;
s|%KERNEL%|${kernel}|g" /boot/arch-uefi.conf.example > /boot/loader/entries/arch-uefi.conf

sed "s|%LINUZ%|${linuz}|g;
s|%KERNEL%|${kernelback}|g" /boot/arch-uefi.conf.example > /boot/loader/entries/arch-uefi-fallback.conf

echo "Bootloader update $(date)" >> /update.log
