#!/bin/bash

set -ex

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
# Satz="Hallo du schöne Welt"
# echo "${Satz:0:5} ${Satz:16}"

#system=$(blkid -L SIMON_OS)
#echo $system

#/dev/sdd
#system1=$(echo "${system:0:8}")
#echo $system1

fdisk -l

read -p "Wie heißt das Laufwerk wo die BTRFS partition erstellt werden soll? sda,sdb,sdc : " system1

#
if cat /proc/mounts | grep /dev/${system1}1 > /dev/null; then
echo "gemountet"
umount /dev/${system1}1
else
echo "nicht gemountet"
fi
#
if cat /proc/mounts | grep /dev/${system1}2 > /dev/null; then
echo "gemountet"
umount /dev/${system1}2
else
echo "nicht gemountet"
fi
#
if cat /proc/mounts | grep /dev/${system1}3 > /dev/null; then
echo "gemountet"
umount /dev/${system1}3
else
echo "nicht gemountet"
fi
#

read -p "Bitte enter druecken zum fortfahren"

fdisk -W always /dev/${system1} <<EOT
p
n




p
w
y
EOT

sleep 2

mkfs.btrfs -L cow_device /dev/${system1}3
