#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
 Satz="Hallo du schöne Welt"
 echo "${Satz:0:5} ${Satz:16}"

system=$(blkid -L SIMON_OS)
echo $system

#/dev/sdd
system1=$(echo "${system:0:8}")
echo $system1

#
if cat /proc/mounts | grep /dev/${system1}1 > /dev/null; then
echo "gemountet"
umount /dev/"$device"1
else
echo "nicht gemountet"
fi
#
if cat /proc/mounts | grep /dev/${system1}2 > /dev/null; then
echo "gemountet"
umount /dev/"$device"2
else
echo "nicht gemountet"
fi
#
if cat /proc/mounts | grep /dev/${system1}3 > /dev/null; then
echo "gemountet"
umount /dev/"$device"2
else
echo "nicht gemountet"
fi
#
if cat /proc/mounts | grep /mnt > /dev/null; then
echo "gemountet"
umount /mnt
else
echo "nicht gemountet"
fi
#

fdisk ${system1} <<EOT
n



p
w
EOT

mkfs.btrfs -L SIM_COW ${system1}3
